# Generated by Django 3.0.3 on 2020-03-07 01:22

from django.db import migrations

def create_country_RF(apps, schema_editor):
    Country = apps.get_model('geo', 'Country')
    rf = Country(name='Российская федерация')
    rf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(create_country_RF),
    ]
