# Generated by Django 3.0.3 on 2020-03-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Краткое описание о работнике'),
        ),
    ]
