# Generated by Django 3.0.3 on 2020-03-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_employee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(default='', max_length=255, verbose_name='Краткое описание о работнике'),
        ),
    ]
