# Generated by Django 3.0.3 on 2020-03-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20200307_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(default='', verbose_name='Краткое описание о работнике'),
        ),
    ]
