# Generated by Django 3.0.3 on 2020-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20200307_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='', max_length=260, verbose_name='Краткое описание об отделе'),
        ),
    ]
