# Generated by Django 3.0.3 on 2020-03-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_auto_20200308_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название отдела'),
        ),
    ]
